import * as fs from 'fs';
import * as path from 'path';
import { type VerificationResult, countErrors, countWarnings } from './bundle.js';

/**
 * Generate a markdown snippet suitable for a GitHub PR description.
 * Uses relative paths for screenshots (assumes artifacts are committed or linked).
 */
export function formatForPR(result: VerificationResult): string {
  const projectName = path.basename(process.cwd());
  const durationSec = Math.round(result.durationMs / 1000);

  let totalErrors = 0;
  let totalWarnings = 0;

  let md = `## Visual Verification — ProofShot

| Page | Status | Screenshot |
|------|--------|------------|
`;

  for (const page of result.pageResults) {
    const errors = countErrors(page.errors);
    const warnings = countWarnings(page.consoleOutput);
    totalErrors += errors;
    totalWarnings += warnings;

    const status = errors > 0 ? '⚠️ Errors' : '✅ OK';
    const relativeSS = path.relative(process.cwd(), page.screenshotPath);
    md += `| \`${page.page}\` | ${status} | ![${page.page}](${relativeSS}) |\n`;
  }

  md += `
**Framework:** ${result.framework} | **Pages:** ${result.pageResults.length} | **Errors:** ${totalErrors} | **Warnings:** ${totalWarnings} | **Duration:** ${durationSec}s
`;

  if (result.videoPath) {
    const relativeVideo = path.relative(process.cwd(), result.videoPath);
    md += `\n**Video:** [Session recording](${relativeVideo})\n`;
  }

  md += `\n<sub>Generated by [ProofShot](https://github.com/AmElmo/proofshot)</sub>\n`;

  return md;
}

/**
 * Write PR-formatted output to a file or stdout.
 */
export function writePRFormat(
  result: VerificationResult,
  outputPath?: string,
): string {
  const md = formatForPR(result);
  if (outputPath) {
    fs.writeFileSync(outputPath, md);
    return outputPath;
  }
  return md;
}

// ─── URL-based PR comment format (for GitHub upload) ───

export interface PRCommentData {
  description: string | null;
  sessionCount: number;
  screenshots: Map<string, string>; // filename → GitHub asset URL
  video: { url: string; renderMode: 'embed' | 'link' } | null;
  recordings?: Array<{
    label: string;
    url: string;
    renderMode: 'embed' | 'link';
  }>;
  errorCount: number;
  verdict: 'PASS' | 'FAIL' | 'INCOMPLETE' | 'BLOCKED';
  verdictReasons: string[];
  userTesting?: Array<{ label: string; instructions: string[] }>;
  branch: string;
  commitSha: string;
}

/**
 * Generate markdown for a GitHub PR comment with embedded uploaded assets.
 * Uses GitHub asset URLs so images and video render inline.
 */
export function formatPRComment(data: PRCommentData): string {
  let md = `## ProofShot Verification\n\n`;

  if (data.description) {
    md += `> ${data.description}\n\n`;
  }

  // Status
  const status = (() => {
    switch (data.verdict) {
      case 'PASS':
        return '✅ Verification passed';
      case 'FAIL':
        return '❌ Verification failed';
      case 'INCOMPLETE':
        return '⚠️ Verification incomplete';
      case 'BLOCKED':
        return '⛔ Verification blocked';
      default: {
        const exhaustiveVerdict: never = data.verdict;
        return exhaustiveVerdict;
      }
    }
  })();
  md += `${status}`;
  if (data.errorCount > 0) {
    md += ` · ${data.errorCount} incident(s)`;
  }
  md += '\n\n';
  if (data.verdictReasons.length > 0) {
    md += data.verdictReasons.map((reason) => `- ${reason}`).join('\n');
    md += '\n\n';
  }

  if (data.userTesting && data.userTesting.length > 0) {
    md += `### User testing\n\n`;
    for (const item of data.userTesting) {
      if (data.userTesting.length > 1) {
        md += `**${item.label}**\n\n`;
      }
      md += item.instructions
        .map((instruction, index) => `${index + 1}. ${instruction}`)
        .join('\n');
      md += '\n\n';
    }
  }

  const recordings: Array<{
    label: string | null;
    url: string;
    renderMode: 'embed' | 'link';
  }> =
    data.recordings ||
    (data.video ? [{ label: null, ...data.video }] : []);
  // GitHub renders uploaded video URLs as playable embeds.
  if (recordings.length > 0) {
    md += `### Recording${recordings.length === 1 ? '' : 's'}\n\n`;
    for (const recording of recordings) {
      if (recordings.length > 1 && recording.label) {
        md += `**${recording.label}**\n\n`;
      }
      if (recording.renderMode === 'embed') {
        md += `${recording.url}\n\n`;
      } else {
        const label = recording.label
          ? `Session recording: ${recording.label}`
          : 'Session recording';
        md += `[${label}](${recording.url})\n\n`;
      }
    }
  }

  // Screenshots
  if (data.screenshots.size > 0) {
    md += `### Screenshots\n\n`;

    if (data.screenshots.size <= 3) {
      for (const [filename, url] of data.screenshots) {
        const label = filename.replace(/\.png$/, '').replace(/^step-/, '');
        md += `**${label}**\n\n`;
        md += `![${label}](${url})\n\n`;
      }
    } else {
      md += `<details>\n<summary>View ${data.screenshots.size} screenshots</summary>\n\n`;
      for (const [filename, url] of data.screenshots) {
        const label = filename.replace(/\.png$/, '').replace(/^step-/, '');
        md += `**${label}**\n\n![${label}](${url})\n\n`;
      }
      md += `</details>\n\n`;
    }
  }

  // Footer
  md += `---\n`;
  md += `<sub>`;
  md += `Branch: \`${data.branch}\``;
  if (data.commitSha) {
    md += ` · Commit: \`${data.commitSha.slice(0, 7)}\``;
  }
  md += ` · ${data.sessionCount} session(s)`;
  md += `</sub>\n`;
  md += `<sub>Generated by [ProofShot](https://github.com/AmElmo/proofshot)</sub>\n`;

  return md;
}
